scrape_configs:
  - job_name: 'Spring Boot Prometheus Grafana Job'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      # For Macos use the below instead of localhost
      - targets: ['docker.for.mac.localhost:8080']
      #- targets: ['localhost:8080']
        labels:
          application: 'Spring Boot Prometheus Grafana'
    basic_auth:
      username: user
      password: password
