scrape_configs:
  - job_name: 'Spring Boot Prometheus Grafana Job'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      #- targets: ['localhost:8080']
      # For Macos M1 the below worked for me instead of localhost
      #- targets: ['docker.for.mac.localhost:8080']
      # For Macos M1, and Intel the below worked for me instead of localhost
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'Spring Boot Prometheus Grafana'
    basic_auth:
      username: user
      password: password
