version: '3.8'

services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus-container
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana
    user: "$UID:$GID"
    container_name: grafana-container
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      #- GF_SERVER_DOMAIN=localhost
      # For Macos M1 the below worked for me instead of localhost
      #- GF_SERVER_DOMAIN=docker.for.mac.localhost
      # For Macos M1, and Intel the below worked for me instead of localhost
      - GF_SERVER_DOMAIN=host.docker.internal
      

      